//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ListadoDeFirmasDSP.gauServices {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/GAU")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TokenModel", Namespace="http://schemas.datacontract.org/2004/07/GAU.Models")]
    [System.SerializableAttribute()]
    public partial class TokenModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AmbienteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AplicacionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AplicativoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long AreaIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CluesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CodigoErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ConexionActivasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ConexionPermitidasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<byte> ContadorErroresLoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CorreoElectronicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaErrorLoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FechaExpPwdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LoginValidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NipConsultaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long NoPersonalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RfcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ListadoDeFirmasDSP.gauServices.RolesModels[] RolesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SesionIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SiglasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoUsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<byte> TipoUsuarioIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UltimaSesionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlDesarrolloField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlProductivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UsuarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long UsuarioIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ambiente {
            get {
                return this.AmbienteField;
            }
            set {
                if ((object.ReferenceEquals(this.AmbienteField, value) != true)) {
                    this.AmbienteField = value;
                    this.RaisePropertyChanged("Ambiente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AplicacionId {
            get {
                return this.AplicacionIdField;
            }
            set {
                if ((this.AplicacionIdField.Equals(value) != true)) {
                    this.AplicacionIdField = value;
                    this.RaisePropertyChanged("AplicacionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Aplicativo {
            get {
                return this.AplicativoField;
            }
            set {
                if ((object.ReferenceEquals(this.AplicativoField, value) != true)) {
                    this.AplicativoField = value;
                    this.RaisePropertyChanged("Aplicativo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Area {
            get {
                return this.AreaField;
            }
            set {
                if ((object.ReferenceEquals(this.AreaField, value) != true)) {
                    this.AreaField = value;
                    this.RaisePropertyChanged("Area");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long AreaId {
            get {
                return this.AreaIdField;
            }
            set {
                if ((this.AreaIdField.Equals(value) != true)) {
                    this.AreaIdField = value;
                    this.RaisePropertyChanged("AreaId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Clues {
            get {
                return this.CluesField;
            }
            set {
                if ((object.ReferenceEquals(this.CluesField, value) != true)) {
                    this.CluesField = value;
                    this.RaisePropertyChanged("Clues");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoError {
            get {
                return this.CodigoErrorField;
            }
            set {
                if ((this.CodigoErrorField.Equals(value) != true)) {
                    this.CodigoErrorField = value;
                    this.RaisePropertyChanged("CodigoError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ConexionActivas {
            get {
                return this.ConexionActivasField;
            }
            set {
                if ((this.ConexionActivasField.Equals(value) != true)) {
                    this.ConexionActivasField = value;
                    this.RaisePropertyChanged("ConexionActivas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ConexionPermitidas {
            get {
                return this.ConexionPermitidasField;
            }
            set {
                if ((this.ConexionPermitidasField.Equals(value) != true)) {
                    this.ConexionPermitidasField = value;
                    this.RaisePropertyChanged("ConexionPermitidas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> ContadorErroresLogin {
            get {
                return this.ContadorErroresLoginField;
            }
            set {
                if ((this.ContadorErroresLoginField.Equals(value) != true)) {
                    this.ContadorErroresLoginField = value;
                    this.RaisePropertyChanged("ContadorErroresLogin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CorreoElectronico {
            get {
                return this.CorreoElectronicoField;
            }
            set {
                if ((object.ReferenceEquals(this.CorreoElectronicoField, value) != true)) {
                    this.CorreoElectronicoField = value;
                    this.RaisePropertyChanged("CorreoElectronico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Curp {
            get {
                return this.CurpField;
            }
            set {
                if ((object.ReferenceEquals(this.CurpField, value) != true)) {
                    this.CurpField = value;
                    this.RaisePropertyChanged("Curp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaErrorLogin {
            get {
                return this.FechaErrorLoginField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaErrorLoginField, value) != true)) {
                    this.FechaErrorLoginField = value;
                    this.RaisePropertyChanged("FechaErrorLogin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaExpPwd {
            get {
                return this.FechaExpPwdField;
            }
            set {
                if ((object.ReferenceEquals(this.FechaExpPwdField, value) != true)) {
                    this.FechaExpPwdField = value;
                    this.RaisePropertyChanged("FechaExpPwd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LoginValido {
            get {
                return this.LoginValidoField;
            }
            set {
                if ((this.LoginValidoField.Equals(value) != true)) {
                    this.LoginValidoField = value;
                    this.RaisePropertyChanged("LoginValido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje {
            get {
                return this.MensajeField;
            }
            set {
                if ((object.ReferenceEquals(this.MensajeField, value) != true)) {
                    this.MensajeField = value;
                    this.RaisePropertyChanged("Mensaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NipConsulta {
            get {
                return this.NipConsultaField;
            }
            set {
                if ((object.ReferenceEquals(this.NipConsultaField, value) != true)) {
                    this.NipConsultaField = value;
                    this.RaisePropertyChanged("NipConsulta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long NoPersonal {
            get {
                return this.NoPersonalField;
            }
            set {
                if ((this.NoPersonalField.Equals(value) != true)) {
                    this.NoPersonalField = value;
                    this.RaisePropertyChanged("NoPersonal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Rfc {
            get {
                return this.RfcField;
            }
            set {
                if ((object.ReferenceEquals(this.RfcField, value) != true)) {
                    this.RfcField = value;
                    this.RaisePropertyChanged("Rfc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ListadoDeFirmasDSP.gauServices.RolesModels[] Roles {
            get {
                return this.RolesField;
            }
            set {
                if ((object.ReferenceEquals(this.RolesField, value) != true)) {
                    this.RolesField = value;
                    this.RaisePropertyChanged("Roles");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SesionId {
            get {
                return this.SesionIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SesionIdField, value) != true)) {
                    this.SesionIdField = value;
                    this.RaisePropertyChanged("SesionId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Siglas {
            get {
                return this.SiglasField;
            }
            set {
                if ((object.ReferenceEquals(this.SiglasField, value) != true)) {
                    this.SiglasField = value;
                    this.RaisePropertyChanged("Siglas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoUsuario {
            get {
                return this.TipoUsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoUsuarioField, value) != true)) {
                    this.TipoUsuarioField = value;
                    this.RaisePropertyChanged("TipoUsuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> TipoUsuarioId {
            get {
                return this.TipoUsuarioIdField;
            }
            set {
                if ((this.TipoUsuarioIdField.Equals(value) != true)) {
                    this.TipoUsuarioIdField = value;
                    this.RaisePropertyChanged("TipoUsuarioId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UltimaSesion {
            get {
                return this.UltimaSesionField;
            }
            set {
                if ((object.ReferenceEquals(this.UltimaSesionField, value) != true)) {
                    this.UltimaSesionField = value;
                    this.RaisePropertyChanged("UltimaSesion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UrlDesarrollo {
            get {
                return this.UrlDesarrolloField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlDesarrolloField, value) != true)) {
                    this.UrlDesarrolloField = value;
                    this.RaisePropertyChanged("UrlDesarrollo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UrlProductivo {
            get {
                return this.UrlProductivoField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlProductivoField, value) != true)) {
                    this.UrlProductivoField = value;
                    this.RaisePropertyChanged("UrlProductivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario {
            get {
                return this.UsuarioField;
            }
            set {
                if ((object.ReferenceEquals(this.UsuarioField, value) != true)) {
                    this.UsuarioField = value;
                    this.RaisePropertyChanged("Usuario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long UsuarioId {
            get {
                return this.UsuarioIdField;
            }
            set {
                if ((this.UsuarioIdField.Equals(value) != true)) {
                    this.UsuarioIdField = value;
                    this.RaisePropertyChanged("UsuarioId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RolesModels", Namespace="http://schemas.datacontract.org/2004/07/GAU.Models")]
    [System.SerializableAttribute()]
    public partial class RolesModels : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RolIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Rol {
            get {
                return this.RolField;
            }
            set {
                if ((object.ReferenceEquals(this.RolField, value) != true)) {
                    this.RolField = value;
                    this.RaisePropertyChanged("Rol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RolId {
            get {
                return this.RolIdField;
            }
            set {
                if ((this.RolIdField.Equals(value) != true)) {
                    this.RolIdField = value;
                    this.RaisePropertyChanged("RolId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="gauServices.IGau")]
    public interface IGau {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGau/GetData", ReplyAction="http://tempuri.org/IGau/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGau/GetData", ReplyAction="http://tempuri.org/IGau/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGau/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IGau/GetDataUsingDataContractResponse")]
        ListadoDeFirmasDSP.gauServices.CompositeType GetDataUsingDataContract(ListadoDeFirmasDSP.gauServices.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGau/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IGau/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<ListadoDeFirmasDSP.gauServices.CompositeType> GetDataUsingDataContractAsync(ListadoDeFirmasDSP.gauServices.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGau/Autentica", ReplyAction="http://tempuri.org/IGau/AutenticaResponse")]
        ListadoDeFirmasDSP.gauServices.TokenModel Autentica(string usuario, string password, string siglas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGau/Autentica", ReplyAction="http://tempuri.org/IGau/AutenticaResponse")]
        System.Threading.Tasks.Task<ListadoDeFirmasDSP.gauServices.TokenModel> AutenticaAsync(string usuario, string password, string siglas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGau/EnviarCorreoReestablecerPassword", ReplyAction="http://tempuri.org/IGau/EnviarCorreoReestablecerPasswordResponse")]
        string EnviarCorreoReestablecerPassword(string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGau/EnviarCorreoReestablecerPassword", ReplyAction="http://tempuri.org/IGau/EnviarCorreoReestablecerPasswordResponse")]
        System.Threading.Tasks.Task<string> EnviarCorreoReestablecerPasswordAsync(string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGau/EnviarCorreoCambioPassword", ReplyAction="http://tempuri.org/IGau/EnviarCorreoCambioPasswordResponse")]
        string EnviarCorreoCambioPassword(string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGau/EnviarCorreoCambioPassword", ReplyAction="http://tempuri.org/IGau/EnviarCorreoCambioPasswordResponse")]
        System.Threading.Tasks.Task<string> EnviarCorreoCambioPasswordAsync(string usuario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGauChannel : ListadoDeFirmasDSP.gauServices.IGau, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GauClient : System.ServiceModel.ClientBase<ListadoDeFirmasDSP.gauServices.IGau>, ListadoDeFirmasDSP.gauServices.IGau {
        
        public GauClient() {
        }
        
        public GauClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GauClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GauClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GauClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public ListadoDeFirmasDSP.gauServices.CompositeType GetDataUsingDataContract(ListadoDeFirmasDSP.gauServices.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<ListadoDeFirmasDSP.gauServices.CompositeType> GetDataUsingDataContractAsync(ListadoDeFirmasDSP.gauServices.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public ListadoDeFirmasDSP.gauServices.TokenModel Autentica(string usuario, string password, string siglas) {
            return base.Channel.Autentica(usuario, password, siglas);
        }
        
        public System.Threading.Tasks.Task<ListadoDeFirmasDSP.gauServices.TokenModel> AutenticaAsync(string usuario, string password, string siglas) {
            return base.Channel.AutenticaAsync(usuario, password, siglas);
        }
        
        public string EnviarCorreoReestablecerPassword(string usuario) {
            return base.Channel.EnviarCorreoReestablecerPassword(usuario);
        }
        
        public System.Threading.Tasks.Task<string> EnviarCorreoReestablecerPasswordAsync(string usuario) {
            return base.Channel.EnviarCorreoReestablecerPasswordAsync(usuario);
        }
        
        public string EnviarCorreoCambioPassword(string usuario) {
            return base.Channel.EnviarCorreoCambioPassword(usuario);
        }
        
        public System.Threading.Tasks.Task<string> EnviarCorreoCambioPasswordAsync(string usuario) {
            return base.Channel.EnviarCorreoCambioPasswordAsync(usuario);
        }
    }
}
